config/routes.rb
DocumentStorage::Application.routes.draw do

  devise_for :users, :path => :auther
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'auther',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :auther_registration do
        get :cancel
      end
  end

  root :to => "users#index"

  resources :users do
    get 'tags/:tag', :to => "documents#index", as: :tag
    put :approve, on: :member
    resources :documents do
      collection do
        get :search
      end
      put :open, on: :member
    end
      
  end 
  

end

app/models/ability.rb
class Ability
        
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    
    can :read, User
    can :update, User, :id => user.id
    # cannot :update, Document
    # cannot :read, Document
    if user.admin?
      can :manage, :all

    else
      can :create, Document
      can :new, Document


      can :edit, Document do |document|
        document.try{:user} == user
      end

      can :update, Document, :user => {:id => user.id}
      can :read, Document, :user => {:id => user.id}
      can :read, Document, :open => true


    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  # has_many :taggings
  # has_many :tags, through: :taggings

  acts_as_taggable
  attr_accessible :user_id, :title, :tag_list, :doc_file, :open
  validates_presence_of :title
  has_attached_file :doc_file
  # validates_attachment_content_type :doc_file, :content_type => ['application/pdf', 'application/msword', 'text/plain']
  # validates_attachment_presence :doc_file

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :document
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :init
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :admin, :approved, :password_confirmation, :remember_me
  
  validates_presence_of :email, :password
  validates_uniqueness_of :email
  
  has_many :documents
  
  acts_as_tagger

def active_for_authentication? 
  super && approved? 
end 

def inactive_message 
  if !approved? 
    :not_approved 
  else 
    super # Use whatever other message 
  end 
end

  private     
  def init
    self.admin = false if self.admin.nil? 
  end
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  # before_filter :get_user
  load_and_authorize_resource :user
  load_and_authorize_resource :document, :through => :user

  def new
    @document = @user.documents.build
  end

  def index
    if params[:search]
      @documnets = Document.tagged_with(params[:tag])

    else
      @documents = Document.all
    end
  end
  
  def search
    @documents = Document.tagged_with(params[:search])
  end

  def open
    @document.update_attribute(:open, 'true')
    redirect_to [@user, @document]
  end
  
  def create
    @document = @user.documents.build(params[:document])
    if @document.save
      flash[:notice] = "Document has been created."
      redirect_to [@user, @document]
    else
      flash[:notice] = "Failed to create document."
      render :action => "new"
    end
  end
  
  def edit

  end
  
  def show

  end
  
  def update  
    if @document.update_attributes(params[:document])
      flash[:notice] = "Update Complete"
      redirect_to [@user, @document]
    else
      flash[:notice] = "Update Failed"
      render :action => "edit"
    end
  end

  def destroy
    if @document.destroy
      flash[:notice] = "document deleted."
      redirect_to @user
    else 
      flash[:notice] = "Can't delete document"
      redirect_to [@user, @document]
    end
  end

  private #get_user should not be called outside contoller
  def get_user
    @user = User.find(params[:user_id])
  end
  private 
  def get_document
    @document = @user.documents.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def approve
    @user = User.find(params[:id])
    @user.update_attribute(:approved, 'true')
    redirect_to @user
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
     if @user.save
    
      flash[:notice] = "Project has been created."
      redirect_to @user 
     else
       flash[:notice] = "Failed to create user"
       render :action => :new
     end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def update  
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Update Complete"
      redirect_to @user
    else
      flash[:notice] = "Update Failed"
      render :action => "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted."
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.haml
-# -@attachment = @document.attachments.build
=form_for [@user, @document], :html => { :multipart => true } do |f|
  %br
  = f.label :title
  = f.text_field :title
  %br
  =f.label :tag_list, "Tags speparated by comma"
  =f.text_field :tag_list
  %br
  = f.label :doc_file
  = f.file_field :doc_file
  %input{:type => "submit", :value => "Save"} 

app/views/documents/edit.html.haml
#userform
  %h2 Edit the document : #{@document.title}
  =render "form"

app/views/documents/index.html.haml
- content_for :title do
  %title DocStor- Documents

%h2 All documents (matching search)
#searches
  %p
    %ol
      = form_tag(search_user_documents_path(current_user), :method => :get) do 
        = label_tag("Search for tags:") 
        = text_field_tag("search", params[:search])
        =submit_tag("Search") 

#Documents
  -@documents.each do |doc|
    %ol
      -if can? :read, doc
        =link_to(doc.title, [doc.user, doc])

      -if can? :manage, :all
        ||--  |  --||
        =link_to("edit", edit_user_document_path(@user,doc))
        ||
        =link_to("delete", [@user,doc], :metod => :delete, :cofirm => "are you sure You want to delete this document")
        -if !doc.open
          ||
          =link_to("make public", open_user_document_path(@user, doc), :method => :put)
      
      -if can? :read, doc
        %p 
          %ol
            Tags: 
            =raw doc.tag_list.map { |t| link_to( t, user_tag_path(doc.user, :tag => t), :method => :index)}.join(', ')

app/views/documents/new.html.haml
-content_for :title do
  %title Add new document

#form
  %h2 Add document
  =render "form"

app/views/documents/search.html.haml
- content_for :title do
  %title DocStor- Documents found

%h2 Document found
#searches
  %p
    %ol
      = form_tag(search_user_documents_path(current_user), :method => :get) do 
        = label_tag("Search for tags:") 
        = search_field_tag("search", params[:search])
        =submit_tag("Search") 

#Documents
  -@documents.each do |doc|
    %ol
      -if can? :read, doc
        =link_to(doc.title, [doc.user, doc])

      -if can? :manage, :all
        ||--  |  --||
        =link_to("edit", edit_user_document_path(@user,doc))
        ||
        =link_to("delete", [@user,doc], :metod => :delete, :cofirm => "are you sure You want to delete this document")
        -if !doc.open
          ||
          =link_to("make public", open_user_document_path(@user, doc), :method => :put)
      
      -if can? :read, doc
        %p 
          %ol
            Tags: 
            =raw doc.tag_list.map { |t| link_to( t, user_tag_path(doc.user, :tag => t), :method => :index)}.join(', ')

app/views/documents/show.html.haml
-content_for :title do
  %title Document view

-status = ""
-if !@document.open?
  -status = "Protected"
-else 
  -status = "Public"


%h2 #{@document.title}

Tags: #{@document.tag_list}
%p 
  =link_to(File.basename(@document.doc_file.path),
    @document.doc_file.url)
%p
  %h5 View Status: #{status}

#footer
  %p
    Uploaded by: #{@document.user.email}

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Document Storage"
    %meta{:content => content_for?(:description) ? yield(:description) : "Document Storage", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    #container.container
      %header

        #user_nav
          -if signed_in?
            =link_to("Back to index", root_path)
            ||--||
            =link_to "My profile", user_path(current_user)
            ||
            =link_to("Upload document", new_user_document_path(current_user))
            || -- ||
            = link_to('Sign out', destroy_user_session_path, :method => "delete")
            || -- || signed in as:
            =current_user.email
            
        #errors
          -if flash[:error]
            %p 
              =flash[:error]
          -if flash[:notice]
            %p
              =flash[:notice]

      #main{:role => "main"}
        %ol
          = yield
      %footer 

app/views/users/_userform.html.haml
%form
  = label :user ,:email, "Email"
  = text_field :user ,:email
  = label :user, :password, "Password"
  = password_field :user, :password

  = label :user, :password, "Password confirm"
  = password_field :user, :confirm_password
  %input{:type => "submit", :value => "Save"}

app/views/users/edit.html.haml
%head
  %title Edit User
%body
  #userform
    %h2 Edit user profile 
    =render "userform"

app/views/users/index.html.haml
-content_for :title do
  %title Users page

%h1 Wellcome to the Document Storage!
#Stright_link
  %ol
    = link_to "All documents", user_documents_path(current_user)

#list_links
  %h2 List all users
  %ol
    %h4 Users needing approval
    - @users.each do |user|
      -if user && !user.approved?
        =link_to(user.email, user)
        ||
        =link_to("Approve", approve_user_path(user), :method => :put)
    
    %h4 Users in system
    -@users.each do |user|
      -if user && user.approved?
        %li
          = link_to(user.email, user)
        
    
  

app/views/users/new.html.haml
!!!
%html
  %head
    %title add new temp
  %body
    %form
      = label :user ,:email, "Email"
      = text_field :user ,:email
      %input{:type => "end", :value => "Send"}

app/views/users/show.html.haml
-satus = ""
-if @user.admin?
  -status = "admin"
-else
  -status = "user"

#profile
  %h2 Profile
  %p
    %h5 Email: #{@user.email}
    %h5 Status: #{status}

  %p
    -if can? :update, @user
      = link_to("edit profile", edit_user_path(@user)) 
      ||

    -if can? :manage, :all
      = link_to("delete user", user_path(@user), :method => :delete, :confirm => "Do you realy want to remove this user?")
    
#Documents

  %h2 Documents
  =link_to("upload document", new_user_document_path(@user))


  %h5 Users documents

  -@user.documents.each do |doc|
    %ol
    -if can? :read, doc
      = link_to(doc.title, [doc.user, doc])
      ||
          
    -if can? :update, doc
      = link_to("edit", edit_user_document_path(doc.user, doc))
      ||

    -if current_user.admin?
      =link_to("delete", [doc.user, doc], :method => :delete)

  %h5 Other documents
  = link_to("All documents", user_documents_path(current_user))

app/views/users/user_page.html.haml
!!!
%html
  %head
    %title user profile

  %body 
    #options
      =link_to ("create user", user_create)
      =link_to ("edit user", user_edit)
      =link_to ("destroy user" user_destroy)

    #information
      %h3 Email - 
        = @user.email
      %br
      % 